name: PopupTranslator

on: [push]

jobs:

  lint:
    runs-on: linux
    steps:
      - name: python-lint
        uses: CyberZHG/github-action-python-lint@0.0.2
     
  build:

    runs-on: linux

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
